### ISSUE TITLE
Userstory #1 : Create a list

### ISSUE THREAD

**Issue by BucherLara** [BucherLara/Capstone-Project#1]
## Value proposition

---

**As a** user
**I need** to see a List with names of social facilities
**to be able to** find the name of the facility that I need. 

## Description

---

![Image](https://user-images.githubusercontent.com/112871731/201745717-2ad057e1-e00d-4949-9384-a4290c12e7bc.png)

## Acceptance criteria

---

- [ ] The user can see the names of all social facilities
- [ ] the list should have it's own headline
- [ ] the names are displayed one below the other

## Tasks

---

- [x] create remote Repository on Github
- [x] connect template and remote Repository
- [x] open feature branch
- [x] create dummy data in json file (with properties:  name, image, adress( with google-link),target, requirements, category)
- [x] create page with a header 
- [x] fetch dummy data (only the names)
- [x] create unordered list with one list item for each facility name

## Complexity Estimation

---

S
