### ISSUE TITLE
Userstory #7: Create NavBar

### ISSUE THREAD

**Issue by BucherLara** [BucherLara/Capstone-Project#13]
## Value proposition

---

**As a** user
**I want to**  switch quickly through the pages
**so that** I don't have to navigate back to the home- page to switch the category.

## Description

---

![Image](https://user-images.githubusercontent.com/112871731/204288283-58c1137e-7ef6-49f5-815d-df4a4c38ec49.png)

## Acceptance criteria

---

- [ ] the categories serve as navigation-items
- [ ] the user can see the navigation-bar at any time except on the homepage
- [ ] the navigation items have the same icons as the navigation on the "home"
- [ ] when the user clicks on the navigation it leads them to the different pages: "Schlafen", "Hygiene", "Medizin": here are the facilities displayed which belong in this category
- [ ] the user can navigate through the pages
- [ ] each page is reachable through the navigation bar
- [ ] the page the user currently visits is marked in the navigation-bar with a different color
- [ ] every page has a navigation on the bottom (except homepage)
- [ ]  every page has its own header at the top with the headline of the page
- [ ] every page has a head with a title which is displayed in the tab

## Tasks

---

- [x] open feature branch
- [x] reuse `Home-Link` and `Favorite-Link` for NavBar
- [x] delete one of those components and rename it as NavBar
- [x] add `Link` from next/link for  Schlafen, Hygiene, Medizin to `Home- `and `Favorite- Link`
- [x] add icons to NavBar
- [x] add `NavBar-Component` to each page: sleep, medicine and hygiene

    - [x] create Layout-Component import Header
    - [x] update Header to display matching heading from each page
    - [x] add NavBar to Layout as footer
    - [x]  implement Layout in app.js
    - [x] hide the NavBar on landing-page
    - [x] create Head- Component
    - [x] each Head should have a <title> and a tag
    - [x]  add Head to each page
    - [x] remove previous headlines
  

## Complexity Estimation

---

M

**Comment by marialitwa** [comment]
Looks pretty good, Lara, keep going! :) I'm just seeing a few minor typos: 
Value Proposition: _homepage_ instead of _home- page_.   
Acceptance criteria: _navigation items_ without a hyphen. Same with _navigation bar_ 
Tasks: last task: _add_, a _d_ is missing. Plus add _icons_, not Icons
🙂
