### ISSUE TITLE
Userstory #8 Layout

### ISSUE THREAD

**Issue by BucherLara** [BucherLara/Capstone-Project#14]
## Value proposition

---

**As a** user
**I want to**  read a title of a page and see a navigation
**so that I** see at a glance what the page is about and can navigate through it quickly.

## Description

---

![Image](https://user-images.githubusercontent.com/112871731/204341532-7f07a811-39d6-44dd-86d6-1318fff6dd5e.png)

## Acceptance criteria

---

- [ ] every page has its own header at the top with the headline of the page
- [ ] every page has the Navigation at the bottom, except of the homepage
- [ ] every page has a head with a title which is displayed in the tab

## Tasks

---

- [ ] open feature branch
- [ ] create `Layout-Component` import `Header`
    - [ ] update `Header` to display matching heading from each page
- [ ] add `NavBar` to `Layout` as footer
- [ ] implement `Layout` in app.js
- [ ] hide the `NavBar` on landing-page
- [ ] create `Head- Component`
   - [ ] each `Head` should have a <title> and a <meta> tag 
- [ ] add `Head` to each page
- [ ] remove previous headlines
  

## Complexity Estimation
s

---
