### ISSUE TITLE
Userstory #9: Styling

### ISSUE THREAD

**Issue by BucherLara** [BucherLara/Capstone-Project#16]
## Value proposition

---

**As a** user
**I want to** have a good looking app
**so that I** like using it.

## Description

---

## Acceptance criteria

---

- [ ] the styling is mobile first (iPhone SE)
- [ ] the app should be accessible for everyone
- [ ] the app should be easy to use

## Tasks

---

- [x] open feature branch
- [x] add icons to google maps link and phone-icon
- [x] use lighthouse for accessibility check
- [x] use Styled Components
- [x] toggle-button in the right corner
- [x] 1/3 img and 2/3 text-content
- [x] facilityname inside `FacilityCard-Component`
- [x] add font
- [x] add color
- [x] add spacing around text-content
- [x] remove add icon and use a link 

## Complexity Estimation
M

---
