### ISSUE TITLE
Userstory #10: fake login

### ISSUE THREAD

**Issue by BucherLara** [BucherLara/Capstone-Project#17]
## Value proposition

---

**As a** user
**I want to** use a login when adding new facilities
**so that I** assure the validation of the information I added. 

## Description

---

![Image](https://user-images.githubusercontent.com/112871731/204778346-45a9383c-72fd-45e0-aa7a-97b4b79c87fc.png)

## Acceptance criteria

---

- [ ] 

## Tasks

---

- [ ] open feature branch
- [ ] reuse `Home-Link` and `Favorite-Link` for NavBar
- [ ] delete one of those components and rename it as NavBar
- [ ] add `Link` from next/link for  Schlafen, Hygiene, Medizin to `Home- `and `Favorite- Link`
- [ ] add icons to NavBar
- [ ] add `NavBar-Component` to each page: sleep, medicine and hygiene
  

## Complexity Estimation

---

s
