### ISSUE TITLE
Userstory #11: delete Function

### ISSUE THREAD

**Issue by BucherLara** [BucherLara/Capstone-Project#18]
# Value proposition

---

**As a** user
**I want** to have the option to delete facilities
**so that I** can delete false information or information which is not up to date anymore.
 

## Description

---

![Image](https://user-images.githubusercontent.com/112871731/204861101-a0164c92-685f-4f6d-83bd-af349ee3f1f7.png)

## Acceptance criteria

---

- [ ] the user can delete facilities
- [ ] the delete button shows a icon
- [ ] the icon is displayed in the `FacilityCard- Component`
- [ ] if the user clicks the delete-button a pop-up is displayed which asks the user: "Bist du dir sicher, dass du diese Einrichtung löschen möchtest?"
- [ ] the pop up has a delete-Button and a cancel-button

## Tasks

---

- [x] open feature branch
- [x] add delete Button to `FacilityCard Component`
- [x] add modal on button click
- [x] add delete and cancel button to modal
   
  

## Complexity Estimation

---

M

**Comment by HendrikNeuschulz** [comment]
nice job !
in my opinion there is nothing to change here.
