### ISSUE TITLE
Userstory #12: upload Image

### ISSUE THREAD

**Issue by BucherLara** [BucherLara/Capstone-Project#19]
Value proposition

---

**As a** user
**I want** to upload the logo of my facility
**so that I** can see the logo next to the information.

## Description

---

![Image](https://user-images.githubusercontent.com/112871731/204865281-5173e405-0309-49d5-be2d-6424ad9c1351.png)

## Acceptance criteria

---

- [ ] the user can upload an image
- [ ] the image should be in jpeg or png format
- [ ] to upload the image the user has to fill in the input form and upload a file 

## Tasks

---

- [ ] open feature branch
- [ ] add image input to `Form Component`
- [ ] connect library cloudinary
- [ ] add size, width, height and position props to set the format for the image 

   
  

## Complexity Estimation

---

L
