### ISSUE TITLE
Userstory #2: Create FacilityCard Component

### ISSUE THREAD

**Issue by BucherLara** [BucherLara/Capstone-Project#2]
#
## Value proposition

---

**As a** user
**I need** to see an image, an adress, target and requirements and the category to each facility name
**to be able to** have more information about the facility.

## Description

---

![Image](https://user-images.githubusercontent.com/112871731/201898675-dff446f5-b7f9-483f-92ca-d485e7d1493d.png)

## Acceptance criteria

---

- [ ] the user can see the details ( 'Kategorie', 'Bild', 'Adresse', 'Zielgruppe', 'Voraussetzungen') for each facility name
- [ ] the adress is a link to google maps
- [ ] if the user clicks on the link they will be lead to the adress in google maps
- [ ] the list should have it's own headline
- [ ] the facility name should be a smaller headline
- [ ] in case there is no picture available put a placeholder

## Tasks

---

- [x] open feature branch
- [x] fetch all dummy data
- [x] create `FacilityCard Component` for each facility name
  - [x] name, picture,adress,target, requirements and category as a prop
  - [x] use Next.js Link component for the adress prop
  - [x] category, name, adress, target, requirements is always required
  - [x] picture is optional, uses placeholder

## Complexity Estimation

---

M
