### ISSUE TITLE
Userstory #3: Create Navigation

### ISSUE THREAD

**Issue by BucherLara** [BucherLara/Capstone-Project#3]
## Value proposition

---

**As a** user
**I want to**  choose between different facility categories
**so that** I am able to find the facility I am looking for more quickly. 

## Description

---

![Image](https://user-images.githubusercontent.com/112871731/201943076-881d502c-1a83-4cfa-87bd-c7dd83c7c992.png)

## Acceptance criteria

---

- [ ] the categories serve as navigation-items
- [ ] the user can see the navigation als "home"- page
- [ ] the navigation- items have icons
- [ ] when the user clicks on the navigation it leads them to the different pages: "Schlafen", "Hygiene", "Medizin": here are the facilities displayed which belong in this category
- [ ] the user can navigate back to the "home"-page with the button "Home"

## Tasks

---

- [x] open feature branch
- [x] create landing page
   - [x] add Navigation-items: "Schlafen", "Hygiene", "Medizin" on landing page
   - [x] create `routing` from navigation-item to the category (page)
   - [x] add icons to navigation-items
   - [x] add basic styling
- [x] add pages: "Schlafen", "Hygiene", "Medizin"
   - [x] add header to each page: 'Einrichtungen für "Schlafen"/"Hygiene"/"Medizin"'
   - [x] render the `FacilityCard Component` on each page for each facility in this category
 - [x] add navigation-item "Home"
  

## Complexity Estimation

---

M

**Comment by gaiisay** [comment]
Tipp: add a back button to the category page, so the user can navigate back to the "Home"-page (don't forget to add to the acceptance criteria how the user navigates back).

**Comment by ahohnsen** [comment]
Hey Lara, 

I have some questions/thoughts regarding your user story:

- Do you already have facilities for all these different categories( "Schlafen", "Medizin", "Hygiene")? I would suggest to only add the navigation items for these categories, once you have facilities which you can display on the respective pages. 
- Also have a look at your value proposition again. The second line should reflect an action and the third line a desired user value. I would suggest something like:

**As a** user
**I want to** choose between different facility categories
**so that** I am able to find the facility I am looking for more quickly.
