### ISSUE TITLE
Userstory #4: Add filter

### ISSUE THREAD

**Issue by BucherLara** [BucherLara/Capstone-Project#4]
## Value proposition

---

**As a** user
**I need** to filter the information
**to be able to** get the specific information that I need.

## Description

---

![Image](https://user-images.githubusercontent.com/112871731/202393365-d0ca7b29-b4da-440c-a0e9-d0ee0444a4cb.png)

## Acceptance criteria

---

- [ ] the user can choose between multiple filter options
- [ ] the user can display all facilities without a filter or the filtered facilities whilst ticking a checkbox
- [ ] the filter options are displayed as checkboxes
- [ ] when the checkbox is ticked, the user can only see the facilities which fulfill the ticked criteria
- [ ] each category has its own three checkboxes to filter 

## Tasks

---

- [x] open feature branch
-  [x] add three Checkboxes for each category 
   - [x] add an input and a label
   - [x] add name, value and label attributes
   - [x] add onClick property
- [x] write `filter function` which is called with onClick prop
- [x] reuse `filter function` for each category

   
  

## Complexity Estimation

---

M

**Comment by FelineHuhn** [comment]
Hey Lara, i like your wireframes and everything is understandable for me. :)

Just a little hint: title of user story = feature = branch ... means: keep the title as short as possible. The checkboxes are part of the filter right? Because of that, I think you don't have to mention the checkboxes in the title, so that it could called just "add filter" or maybe "add category filter" (or for which kind of content is the filter?)

**Comment by GregOnOff** [comment]
seems good to me :)

**Comment by ahohnsen** [comment]
Hey Lara,

Nice feature :) One little thing:

In the acceptance criteria you are talking about checkboxes and in the tasks about radiobuttons. Which one will you use? If you use radiobuttons, please keep in mind that it is not possible to deselect a radiobutton. Meaning, when I click on the filter option "sofort" and afterwards I want to see again all facilities without any filter, that would not be possible. I could only select another filter option instead of "sofort".

 As well, radiobuttons should be used if the user should only be able to select one choice. If you want the user to be able to search facilities matching two filter options (e.g. "sofort" and "mit Hund") you would need to use checkboxes instead. 

I suggest that you think about, which type of filter would be most useful for your user (e.g. single-choice, multiple-choice) and then you can decide which elements you are going to use. 🙂 It would be good to mention in the acceptance criteria if the user can select only one option or multiple filter options.

**Comment by ahohnsen** [comment]
Nice update 🙂 Only thing I could "complain about" is, that in your wireframe it looks more like radiobuttons than checkboxes ;)
