### ISSUE TITLE
Userstory #5: Toggle-function

### ISSUE THREAD

**Issue by BucherLara** [BucherLara/Capstone-Project#8]
## Value proposition

---

**As a** user
**I want** to save my favorites
**so that I** have my own overview about the specific information I need. 

## Description

---

![Image](https://user-images.githubusercontent.com/112871731/203097865-02b1e622-4ace-4a0e-81dd-df7edf784a77.png)

## Acceptance criteria

---

- [ ] each facility with it's details has it's own "Favoriten"button
- [ ] if the user clicks on the "Favoriten" button, the facility with it's details is saved on the "Favoriten" page
- [ ] if the user clicks the same button again it will be removed from the "Favoriten" and the "Favoriten" page
- [ ] the user can navigate to the "Favoriten" Page with a navigation-item "Favoriten" which appears on all pages next to the "home" navigation-item

## Tasks

---

- [x] open feature branch
- [x] add "Favoriten" button to each `FacilityCard-Component`
   - [x] add toggle function with prop: isBookmarked and a boolean value
- [x] add "Favoriten" page
- [x] add Navigation Item "Favoriten"

   
  

## Complexity Estimation

---

M
