### ISSUE TITLE
Userstory #6: Add new facilities

### ISSUE THREAD

**Issue by BucherLara** [BucherLara/Capstone-Project#9]
# Value proposition

---

**As a** user
**I want** to add new facilities
**so that I** have more facilities to select the most appropriate one for me.

## Description

---

![Image](https://user-images.githubusercontent.com/112871731/203500985-00d79313-cf11-4bfd-a0df-42eaddaa530b.png)

## Acceptance criteria

---

- [ ] the user can add new facilities 
- [ ] if the user clicks on the "hinzufügen"-Button on the landing page they will be directed to an input-form to add new facilities 
- [ ] the user has to fill out the form: "Name", "Zielgruppe","Zugangsvoraussetzungen", "Adresse", "Telefonnummer" is required
- [ ] the user has to choose/tick the "Kategorie" which fits the most, "Kategorie" is required and ticked by default
- [ ] if the user chooses the "Kategorie", the related filter-criteria appears and the user is able to choose (out of the checkboxes) which filter can be applied on the facility
- [ ] the user can upload images (jpeg, png) and also add a google link (url) of the facility adress
- [ ] if the user filled out all the required fields in the form they can click the "hinzufügen"-Button and add the new facility to the belonging "Kategorie", after submitting they will be redirected to the "home"- page
- [ ] the user can't submit the form if they didn't fill out all the required fields, also they are not able to submit empty fields or fields which need to be in a specific format
- [ ] the user is able to leave/close the form-page whilst clicking on the x- icon 

## Tasks

---

- [x] open feature branch
- [x] create `Form-Component` with: form, fieldset, label, input, checkboxes (maybe Dropdown instead) and submit button
- [x] add Eventhandler on Submit-button 
- [x] add Link to landing-page (hinzufügen- Button) 
- [x] add required props and form validation 
- [x] create add function 
- [x] add "x"- icon and Link back to "home" page

   
  

## Complexity Estimation

---

L

**Comment by EugenMoser** [comment]
very good
